class CityService {
  static const List<String> cities = [
    "Boston",
    "Worcester",
    "Springfield",
    "Cambridge",
    "Lowell",
    "Brockton",
    "New Bedford",
    "Quincy",
    "Lynn",
    "Fall River",
    "Newton",
    "Somerville",
    "Lawrence",
    "Framingham",
    "Haverhill",
    "Waltham",
    "Plymouth",
    "Malden",
    "Brookline",
    "Medford",
    "Taunton",
    "Weymouth Town",
    "Chicopee",
    "Revere",
    "Peabody",
    "Methuen Town",
    "Everett",
    "Arlington",
    "Attleboro",
    "Barnstable Town",
    "Salem",
    "Billerica",
    "Pittsfield",
    "Beverly",
    "Leominster",
    "Westfield",
    "Fitchburg",
    "Woburn",
    "Holyoke",
    "Amherst Town",
    "Chelsea",
    "Marlborough",
    "Shrewsbury",
    "Braintree Town",
    "Andover",
    "Natick",
    "Watertown Town",
    "Chelmsford",
    "Randolph Town",
    "Dartmouth",
    "Franklin Town",
    "Lexington",
    "Dracut",
    "North Andover",
    "Needham",
    "Tewksbury",
    "Falmouth",
    "Gloucester",
    "Norwood",
    "North Attleborough Town",
    "Milford",
    "Wellesley",
    "Stoughton",
    "Agawam Town",
    "Northampton",
    "West Springfield Town",
    "Saugus",
    "Burlington",
    "Melrose",
    "Milton",
    "Danvers",
    "Bridgewater Town",
    "Wakefield",
    "Belmont",
    "Marshfield",
    "Walpole",
    "Dedham",
    "Reading",
    "Middleborough",
    "Easton",
    "Westford",
    "Mansfield",
    "Hingham",
    "Acton",
    "Stoneham",
    "Canton",
    "Wilmington",
    "Yarmouth",
    "Winchester",
    "Wareham",
    "Ludlow",
    "Gardner",
    "Marblehead",
    "Sandwich",
    "Norton",
    "Hudson",
    "Bourne",
    "Sudbury",
    "Holden",
    "Westborough",
    "Grafton",
    "Concord",
    "Scituate",
    "Sharon",
    "Winthrop Town",
    "Pembroke",
    "Newburyport",
    "Somerset",
    "Hopkinton",
    "Rockland",
    "Foxborough",
    "Ashland",
    "South Hadley",
    "Amesbury Town",
    "Greenfield",
    "Bellingham",
    "Webster",
    "Southbridge Town",
    "Auburn and Swansea",
    "Northbridge",
    "Abington",
    "East Longmeadow and Westwood",
    "Fairhaven",
    "Westport",
    "Easthampton Town",
    "Duxbury",
    "Longmeadow",
    "North Reading",
    "Seekonk",
    "Swampscott",
    "Whitman",
    "Belchertown",
    "Northborough",
    "Holliston",
    "Wilbraham",
    "Hanover",
    "East Bridgewater",
    "Raynham",
    "Mashpee",
    "Bedford",
    "Uxbridge",
    "Ipswich",
    "Oxford",
    "Clinton",
    "Dennis",
    "Wayland",
    "Millbury",
    "Kingston",
    "Charlton",
    "Medway",
    "Lynnfield",
    "Medfield",
    "North Adams",
    "Tyngsborough",
    "Rehoboth",
    "Palmer Town",
    "Harwich",
    "Pepperell",
    "Weston",
    "Spencer",
    "Wrentham",
    "Norfolk",
    "Carver",
    "Dudley",
    "Athol",
    "Lunenburg",
    "Lakeville",
    "Groton",
    "Leicester",
    "Nantucket",
    "Norwell",
    "Holbrook",
    "Maynard",
    "Hanson",
    "Winchendon",
    "Acushnet",
    "Hull",
    "Littleton",
    "Southborough",
    "Middleton",
    "Ware",
    "Brewster",
    "Southwick",
    "Sturbridge",
    "Sutton",
    "Townsend",
    "Salisbury",
    "Freetown",
    "Blackstone",
    "Plainville",
    "Douglas",
    "Rutland",
    "Monson",
    "Georgetown",
    "Cohasset",
    "Boxford",
    "Millis",
    "Montague",
    "Ayer",
    "Sterling",
    "Templeton",
    "Adams",
    "Hamilton",
    "West Boylston",
    "Lancaster",
    "Upton",
    "Westminster",
    "Dighton",
    "Halifax",
    "Orange",
    "Shirley",
    "Williamstown",
    "Rockport",
    "West Bridgewater",
    "Stow",
    "Newbury",
    "Great Barrington",
    "Merrimac",
    "Lincoln",
    "Groveland",
    "Berkley",
    "Topsfield",
    "Harvard",
    "Dalton",
    "Rowley",
    "Mattapoisett",
    "Granby",
    "Ashburnham",
    "Southampton",
    "Mendon",
    "Dover",
    "Chatham",
    "Hopedale",
    "Orleans",
    "Lee",
    "Boxborough",
    "Rochester",
    "Barre",
    "Manchester-by-the-Sea",
    "Bolton",
    "Hadley",
    "Carlisle",
    "Wenham",
    "Warren",
    "Hampden",
    "Marion",
    "Deerfield",
    "Lenox",
    "Paxton",
    "Eastham",
    "North Brookfield",
    "Hubbardston",
    "Oak Bluffs",
    "West Newbury",
    "Boylston",
    "Avon",
    "Edgartown",
    "Sherborn",
    "Tisbury",
    "Essex",
    "West Brookfield",
    "Brimfield",
    "Wellfleet",
    "Sunderland",
    "Nahant",
    "Princeton",
    "Brookfield",
    "Dunstable",
    "Berlin",
    "Hatfield",
    "Millville",
    "Ashby",
    "Sheffield",
    "Cheshire",
    "Hardwick",
    "Plympton",
    "Northfield",
    "Provincetown",
    "Lanesborough",
    "Williamsburg",
    "Holland",
    "West Tisbury",
    "Huntington",
    "East Brookfield",
    "Wales",
    "Buckland",
    "Bernardston",
    "Becket",
    "Phillipston",
    "Shutesbury",
    "Leverett",
    "Conway",
    "Stockbridge",
    "Ashfield",
    "Clarksburg",
    "Colrain",
    "Gill",
    "Hinsdale",
    "Westhampton",
    "Granville",
    "Erving",
    "Oakham",
    "Chester",
    "Russell",
    "New Marlborough",
    "Whately",
    "Egremont",
    "Royalston",
    "Otis",
    "Shelburne",
    "Richmond",
    "Pelham",
    "Chilmark",
    "Worthington",
    "Chesterfield",
    "West Stockbridge",
    "New Braintree",
    "Petersham",
    "Charlemont",
    "Truro",
    "New Salem",
    "Blandford",
    "Cummington",
    "Windsor",
    "Montgomery",
    "Sandisfield",
    "Goshen",
    "Wendell",
    "Warwick",
    "Florida",
    "Peru",
    "Monterey",
    "Savoy",
    "Plainfield",
    "Leyden",
    "Aquinnah",
    "Heath",
    "Hancock",
    "Tyringham",
    "Washington",
    "Tolland",
    "Rowe",
    "Hawley",
    "Alford",
    "Middlefield",
    "New Ashford",
    "Mount Washington",
    "Monroe",
    "Gosnold"
  ];

  static List<String> getSuggestions(String query) {
    List<String> matches = [];
    matches.addAll(cities);
    matches.retainWhere(
        (String city) => city.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}
